FROM ubuntu:latest

RUN apt-get update && apt-get -y upgrade

RUN apt install -y mysql-server 

RUN apt install mysql-client

CMD ["bash"]

# https://obu4alka.ru/kak-nastroit-phpmyadmin-na-nginx-i-php-7.html
# настройка PHPMYADMIN