apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: default
  labels:
    app: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  loadBalancerIP: 192.168.49.100
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template: 
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
